#!/bin//tcsh 
source /apps/root/PRO.old/setroot_CUE.csh
setenv file shms_pointtarg_7p5deg_2gev_wc_mscat_vac
foreach q2 (0.955 0.965 0.975 0.985 0.995 1.015 1.025 1.035 1.045 1.055)
setenv quad shms_vary_Q1_1.00_Q2_${q2}_Q3_1.00
cd src
echo ${quad}
echo ${file}
cd shms
ln -sf cosy/${quad}_forward.dat shms-2011-26cm-monte_ideal_6ord_forward.dat
ln -sf cosy/${quad}_recon.dat shms-2011-26cm-monte_ideal_6ord_recon.dat
ls -lrt
cd ..
mc_single_arm << endofinput >! ../runout/${file}.out
${file}
endofinput
cd ..
h2root worksim/${file}.rzdat worksim/${file}_${quad}.root
echo  worksim/${file}_${quad}.root
end

